// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/gfaraj/brewme.recipes.service/dao"
	"github.com/gfaraj/brewme.recipes.service/web"
)

// Injectors from wire.go:

func InitializeRecipeDao() dao.RecipeDao {
	recipeDao := dao.NewRecipeDaoMock()
	return recipeDao
}

func InitializeRecipeController() *web.RecipeController {
	recipeDao := InitializeRecipeDao()
	recipeController := web.NewRecipeController(recipeDao)
	return recipeController
}
